# Generated by Django 6.1.1 on 2026-09-28 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_guestbookentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pages.guestbookentry'),
        ),
    ]
